routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    Route::name('dashboard')->get('/', 'HomeController@index');
    // Users
    Route::resource('users', 'UsersController');
    //
    Route::resource('locations', 'LocationsController');
    // Reset Password Requests
    Route::resource('resets', 'ResetsController', ['only' => ['index', 'edit']]);
    Route::delete('resets/{id}', 'ResetsController@destroy')->name('resets.destroy');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Location.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    protected $fillable = ['name', 'latitude', 'longitude', 'type'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function locationTrackers()
    {
        return $this->hasMany(LocationTracker::class);
    }
}

app/Http/Controllers/API/LocationsController.php
<?php

namespace App\Http\Controllers\API;

use App\Location;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LocationsController extends Controller
{
    /**
     * @SWG\Get(
     *   path="/locations",
     *   tags={"Locations"},
     *   operationId="locations",
     *   summary="Locations",
     *   @SWG\Response(
     *    response=200,
     *    description="success",
     *   ),
     *   @SWG\Response(
     *    response=400,
     *    description="error",
     *   ),
     *  )
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        $locations = Location::get();
        return response()->json([
            'locations' => $locations
        ]);
    }
}

app/Http/Controllers/Admin/LocationsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\LocationRequest;
use App\Location;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LocationsController extends Controller
{
    public function index()
    {
        $locations = Location::where('type', 'office')->latest()->paginate(10);

        return view('admin.locations.index', compact('locations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.locations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param LocationRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(LocationRequest $request)
    {
        Location::create($request->input());

        return redirect()->route('admin.locations.index')->with('success', 'New Location Created Successfully !');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Location $location
     * @return \Illuminate\Http\Response
     */
    public function edit(Location $location)
    {
        return view('admin.locations.edit', compact('location'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param LocationRequest $request
     * @param Location $location
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(LocationRequest $request, Location $location)
    {
        $location->update($request->input());

        return redirect()->route('admin.locations.index')->with('success', 'Location Data Updated Successfully !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Location $location
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Location $location)
    {
        $location->delete();

        return redirect()->route('admin.locations.index')->with('success', 'Location Deleted Successfully !');
    }
}

resources/views/admin/locations/_form.blade.php
<div class="box-body">
    <input type="hidden" name="id" value="{{ isset($location) ? $location->id : null }}">
    <div class="form-group">
        {!! Form::label('name', 'Name') !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('latitude', 'latitude') !!}
        {!! Form::text('latitude', null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('longitude', 'longitude') !!}
        {!! Form::text('longitude', null, ['class' => 'form-control']) !!}
    </div>
    {!! Form::hidden('type', 'office', ['class' => 'form-control']) !!}
</div>

<div class="box-footer">
    {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
</div>

resources/views/admin/locations/create.blade.php
@extends('admin.layouts.app')

@section('page.title', 'Locations')
@section('page.description', 'Create New Location')
@section('page.breadcrumb')
    <li><a href="{{ route('admin.locations.index') }}">Locations</a></li>
    <li class="active">Add New</li>
@stop

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">New location</h3>
        </div>
        {!! Form::open(['url' => route('admin.locations.store')]) !!}
        @include('admin.locations._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/admin/locations/edit.blade.php
@extends('admin.layouts.app')

@section('page.title', 'Edit Location')
@section('page.description', 'update an location information')
@section('page.breadcrumb')
    <li><a href="{{ route('admin.locations.index') }}">Locations</a></li>
    <li class="active">Edit location</li>
@stop

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Edit Location</h3>
        </div>
        {!! Form::model($location, ['method' => 'PATCH', 'url' => route('admin.locations.update', $location->id)]) !!}
        @include('admin.locations._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/admin/locations/index.blade.php
@extends('admin.layouts.app')
@section('page.title', 'Locations')
@section('page.description')
    <a class="btn btn-success btn-xs" href="{{ route('admin.locations.create') }}"><i class="fa fa-plus"></i> New</a>
@stop
@section('page.breadcrumb')
    <li class="active">Locations</li>
@stop

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Locations</h3>
            <div class="box-tools">
                {{--<a href="{{ route('admin.areas.export') }}" class="btn btn-box-tool"><i class="fa fa-download"></i></a>--}}
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        @if(count($locations))
            <div class="box-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>latitude</th>
                        <th>longitude</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($locations as $location)
                        <tr>
                            <td>{{ $location->name }}</td>
                            <td>{{ $location->latitude }}</td>
                            <td>{{ $location->longitude }}</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="{{ route('admin.locations.edit', $location->id) }}">
                                    <i class="fa fa-pencil"></i>
                                    Edit
                                </a>
                                @if($location->id != 1)
                                    @include('admin.partials.delete', [
                                        'id' => $location->id,
                                        'route' => route('admin.locations.destroy', $location->id),
                                        'title' => $location->name,
                                        'body' => 'You cannot undo this action.'
                                    ])
                                @endif
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="box-footer">
                {!! $locations->render() !!}
            </div>
    </div>
    @else
        @include('admin.partials.empty', ['message' => "You didn't create any Users yet."])
    @endif
@stop