routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    Route::name('dashboard')->get('/', 'HomeController@index');
    // Users
    Route::resource('users', 'UsersController');
    //
    Route::resource('locations', 'LocationsController');
    // Reset Password Requests
    Route::resource('resets', 'ResetsController', ['only' => ['index', 'edit']]);
    Route::delete('resets/{id}', 'ResetsController@destroy')->name('resets.destroy');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Reset.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reset extends Model
{
    protected $fillable = ['email', 'reset'];
}

app/Http/Controllers/API/ResetsController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Requests\API\ResetRequest;
use App\Http\Controllers\Controller;
use App\Reset;

class ResetsController extends Controller
{
    /**
     * @SWG\Post(
     *   path="/resets",
     *   tags={"Reset Password Request"},
     *   operationId="reset_password",
     *   summary="Reset Password",
     *   @SWG\Parameter(
     *    name="email",
     *    in= "formData",
     *    required=true,
     *    type="string",
     *    description="User Email",
     *  ),
     *   @SWG\Response(
     *    response=200,
     *    description="success",
     *   ),
     *   @SWG\Response(
     *    response=400,
     *    description="error",
     *   ),
     *  )
     * @param ResetRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(ResetRequest $request)
    {
        Reset::create($request->input());

        return response()->json([
            'message' => 'Request Send Successfully !'
        ]);
    }
}

app/Http/Controllers/Admin/ResetsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Reset;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ResetsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $resets =Reset::latest()->paginate(10);

        return view('admin.resets.index', compact('resets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $reset = Reset::where('id', $id)->first();
        $reset->delete();

        return redirect()->route('admin.resets.index')->with('success', 'Reset Request deleted Successfully !');
    }
}

resources/views/admin/resets/index.blade.php
@extends('admin.layouts.app')
@section('page.title', 'Reset Requests')
@section('page.description')
    {{--<a class="btn btn-success btn-xs" href="{{ route('admin.resets.create') }}"><i class="fa fa-plus"></i> New</a>--}}
@stop
@section('page.breadcrumb')
    <li class="active">Reset Requests</li>
@stop

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Reset Requests</h3>
            <div class="box-tools">
                {{--<a href="{{ route('admin.areas.export') }}" class="btn btn-box-tool"><i class="fa fa-download"></i></a>--}}
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        @if(count($resets))
            <div class="box-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Email</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($resets as $reset)
                        <tr>
                            <td>{{ $reset->email }}</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="{{ route('admin.resets.edit', $reset->email) }}">
                                    <i class="fa fa-pencil"></i>
                                    Edit
                                </a>
                                @include('admin.partials.delete', [
                                    'id' => $reset->id,
                                    'route' => route('admin.resets.destroy', $reset->id),
                                    'title' => $reset->email,
                                    'body' => 'You cannot undo this action.'
                                ])
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="box-footer">
                {!! $resets->render() !!}
            </div>
    </div>
    @else
        @include('admin.partials.empty', ['message' => "No Reset Requests Received yet."])
    @endif
@stop