routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    Route::name('dashboard')->get('/', 'HomeController@index');
    // Users
    Route::resource('users', 'UsersController');
    //
    Route::resource('locations', 'LocationsController');
    // Reset Password Requests
    Route::resource('resets', 'ResetsController', ['only' => ['index', 'edit']]);
    Route::delete('resets/{id}', 'ResetsController@destroy')->name('resets.destroy');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>ASM | @yield('page.title', 'Dashboard')</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="/build/css/vendor.css">
    <link rel="stylesheet" href="/build/css/dashboard.css">
    @yield('styles')

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-purple sidebar-mini">
    <div class="wrapper" id="app">
        @include('admin.layouts.header')
        @include('admin.layouts.sidebar')

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @yield('page.title')
                    <small>@yield('page.description')</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                    @yield('page.breadcrumb')
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">
                @include('admin.partials.alerts')
                @yield('content')
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 0.0.0
            </div>
            <strong>Copyright &copy; 2018 <a href="#">Davinci Agency</a>.</strong> All rights
            reserved.
        </footer>
    </div>
    <!-- ./wrapper -->

    <script src="/build/js/vendor.js"></script>
    <script src="/build/js/dashboard.js"></script>
    @yield('scripts')
</body>
</html>

resources/views/admin/layouts/header.blade.php
<header class="main-header">
    <a href="{{ route('welcome') }}" class="logo">
        <span class="logo-lg">ASM</span>
        <span class="logo-min"><b>N</b></span>
    </a>
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li>
                    <a href="" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out"></i> <span>Sign out</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/build/img/avatar.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::check() ? Auth::user()->name : 'Dev' }}</p>
            </div>
        </div>
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li class="{{ isRouteActive('admin.dashboard') ? ' active' : '' }}"><a href="{{ route('admin.dashboard') }}"> <i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
            <li class="treeview{{ isRouteActive('admin.users.*') ? ' active' : '' }}">
                <a href="#">
                    <i class="fa fa-users"></i><span>Users</span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.users.index') }}">All Users</a></li>
                    <li><a href="{{ route('admin.users.create') }}">Create User</a></li>
                </ul>
            </li>
            <li class="treeview{{ isRouteActive('admin.locations.*') ? ' active' : '' }}">
                <a href="#">
                    <i class="fa fa-users"></i><span>Locations</span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.locations.index') }}">All Locations</a></li>
                    <li><a href="{{ route('admin.locations.create') }}">Create Location</a></li>
                </ul>
            </li>
            <li class="{{ isRouteActive('admin.customers.index') ? ' active' : '' }}"><a href="{{ route('admin.resets.index') }}"> <i class="fa fa-users"></i> <span>Reset Passwords</span></a></li>
            {{--<li class="treeview{{ isRouteActive('admin.products.*') ? ' active' : '' }}">
                <a href="#">
                    <i class="fa fa-cubes"></i><span>Products</span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.products.index') }}">Products</a></li>
                    <li><a href="{{ route('admin.components.index') }}">Components</a></li>
                    <li><a href="{{ route('admin.modifiers.index') }}">Modifiers</a></li>
                </ul>
            </li>
            <li class="{{ isRouteActive('admin.customers.index') ? ' active' : '' }}"><a href="{{ route('admin.customers.index') }}"> <i class="fa fa-users"></i> <span>Customers</span></a></li>
            <li class="{{ isRouteActive('admin.daily_summary') ? ' active' : '' }}"><a href="{{ route('admin.daily_summary') }}"> <i class="fa fa-users"></i> <span>Daily Summery</span></a></li>
            <li><a href="#"><i class="fa fa-info"></i> <span>Settings</span></a></li>--}}
            <li>
                <a href="" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out"></i> <span>Sign out</span></a>
            </li>
        </ul>
    </section>
</aside>