routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    Route::name('dashboard')->get('/', 'HomeController@index');
    // Users
    Route::resource('users', 'UsersController');
    //
    Route::resource('locations', 'LocationsController');
    // Reset Password Requests
    Route::resource('resets', 'ResetsController', ['only' => ['index', 'edit']]);
    Route::delete('resets/{id}', 'ResetsController@destroy')->name('resets.destroy');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'type', 'admin', 'manager_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function locationTrackers()
    {
        return $this->hasMany(LocationTracker::class);
    }

    public function days()
    {
        return $this->hasMany(Day::class);
    }

    public function manager()
    {
        return $this->belongsTo(User::class, 'manager_id');
    }

    public function users()
    {
        return $this->hasMany(User::class, 'manager_id');
    }
}

app/Http/Controllers/API/UsersController.php
<?php

namespace App\Http\Controllers\API;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{
    /**
     * @SWG\Get(
     *   path="/managers",
     *   tags={"Managers"},
     *   operationId="managers",
     *   summary="get All Managers",
     *   @SWG\Response(
     *    response=200,
     *    description="success",
     *   ),
     *   @SWG\Response(
     *    response=400,
     *    description="error",
     *   ),
     *  )
     * @return \Illuminate\Http\JsonResponse
     */
    public function managers()
    {
        $managers = User::where(['type'=> 'management', 'admin' => 0])->get(['id', 'name']);
        return response()->json([
            'managers' => $managers
        ]);
    }

    /**
     * @SWG\Get(
     *   path="/sales",
     *   tags={"sales"},
     *   operationId="sales",
     *   summary="get All sales Users For this Manager",
     *  @SWG\Parameter(
     *    name="manager_id",
     *    in="query",
     *    required=true,
     *    type="integer",
     *    format="int",
     *    description="Manager id",
     *  ),
     *   @SWG\Response(
     *    response=200,
     *    description="success",
     *   ),
     *   @SWG\Response(
     *    response=400,
     *    description="error",
     *   ),
     *  )
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function sales(Request $request)
    {
        $sales = User::where(['type'=> 'sales', 'admin' => 0, 'manager_id' => $request->input('manager_id')])
            ->get(['id', 'name']);
        return response()->json([
            'sales' => $sales
        ]);
    }

}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\UserRequest;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('admin', false)->latest()->paginate(10);

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $managers = User::where(['type'=> 'management', 'admin' => 0])->pluck('name', 'id');
        return view('admin.users.create', compact('managers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param UserRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $user = new User($request->except('password'));
        $user->password = bcrypt($request->get('password'));
        $user->save();

        return redirect()->route('admin.users.index')->with('success', 'New User Created Successfully !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $managers = User::where(['type'=> 'management', 'admin' => 0])->pluck('name', 'id');
        return view('admin.users.edit', compact('user', 'managers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UserRequest $request
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, User $user)
    {
        $user->update($request->except('password'));
        $user->password = bcrypt($request->get('password'));
        $user->update();

        return redirect()->route('admin.users.index')->with('success', 'User Data Updated Successfully !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.users.index')->with('success', 'User Deleted Successfully !');
    }
}

resources/views/admin/users/_form.blade.php
<div class="box-body">
    <input type="hidden" name="id" value="{{ isset($user) ? $user->id : null }}">
    <div class="form-group">
        {!! Form::label('manager_id', 'Manager') !!}
        {!! Form::select('manager_id', $managers, null, ['class' => 'form-control','placeholder' => 'select Manager']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('name', 'Name') !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('email', 'Email') !!}
        {!! Form::text('email', null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('password', 'Password') !!}
        {!! Form::password('password', null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('type', 'User Type') !!}
        {!! Form::select('type', ['sales' => 'sales', 'management'=> 'management'], null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="box-footer">
    {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
</div>

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')

@section('page.title', 'Users')
@section('page.description', 'Create New User')
@section('page.breadcrumb')
    <li><a href="{{ route('admin.users.index') }}">Users</a></li>
    <li class="active">Add New</li>
@stop

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">New User</h3>
        </div>
        {!! Form::open(['url' => route('admin.users.store'),'files'=>'true']) !!}
        @include('admin.users._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('page.title', 'Edit User')
@section('page.description', 'update an user information')
@section('page.breadcrumb')
    <li><a href="{{ route('admin.users.index') }}">Users</a></li>
    <li class="active">Edit User</li>
@stop

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Edit User</h3>
        </div>
        {!! Form::model($user, ['method' => 'PATCH', 'url' => route('admin.users.update', $user->id)]) !!}
        @include('admin.users._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')
@section('page.title', 'Users')
@section('page.description')
    <a class="btn btn-success btn-xs" href="{{ route('admin.users.create') }}"><i class="fa fa-plus"></i> New</a>
@stop
@section('page.breadcrumb')
    <li class="active">Users</li>
@stop

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Users</h3>
            <div class="box-tools">
                {{--<a href="{{ route('admin.areas.export') }}" class="btn btn-box-tool"><i class="fa fa-download"></i></a>--}}
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        @if(count($users))
            <div class="box-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Type</th>
                        <th>Manager</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->type }}</td>
                            <td>{{ $user->manager? $user->manager->name : '' }}</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="{{ route('admin.users.edit', $user->id) }}">
                                    <i class="fa fa-pencil"></i>
                                    Edit
                                </a>
                                @include('admin.partials.delete', [
                                    'id' => $user->id,
                                    'route' => route('admin.users.destroy', $user->id),
                                    'title' => $user->name,
                                    'body' => 'You cannot undo this action.'
                                ])
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="box-footer">
                {!! $users->render() !!}
            </div>
    </div>
    @else
        @include('admin.partials.empty', ['message' => "You didn't create any Users yet."])
    @endif
@stop